#!/bin/sh
if uname -s | egrep -iq 'bsd'; then export EXPR_COMPAT=1; fi

# enable debug mode
if [ "$DEBUG" = "yes" ]; then
	set -x
fi

# The sed expression here replaces all backslashes by forward slashes.
# This helps our Windows users, while not bothering our Unix users.
export GITFLOW_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")


usage() {
	echo "usage: flow <subcommand>"
	echo
	echo "Available subcommands are:"
	echo "   init      Initialize a new git repo with support for the branching model."
	echo "   feature   Manage your feature branches."
	echo "   release   Manage your release branches."
	echo "   hotfix    Manage your hotfix branches."
	echo "   update    Update flow version"
	echo
	echo "Try 'flow <subcommand> help' for details."
}

main() {


	if [ $# -lt 1 ]; then
		usage
		exit 1
	fi

	# load common functionality
	. "$GITFLOW_DIR/gitflow-common"

	# This environmental variable fixes non-POSIX getopt style argument
	# parsing, effectively breaking git-flow subcommand parsing on several
	# Linux platforms.
	export POSIXLY_CORRECT=1

	# use the shFlags project to parse the command line arguments
	. "$GITFLOW_DIR/gitflow-shFlags"
    FLAGS_PARENT="git flow"


    # allow user to request git action logging
    DEFINE_boolean show_commands false 'show actions taken (git commands)' g

    # do actual parsing
    FLAGS "$@" || exit $?
    eval set -- "${FLAGS_ARGV}"

    # sanity checks
    SUBCOMMAND="$1"

	if [ ! -e "$GITFLOW_DIR/git-flow-$SUBCOMMAND" ]; then
        echo "$@"
        git_do "$@" 
        if [ $? -ne 0 ]; then
    		usage
    		exit 1

        else
            exit 0
        fi
	fi

    shift
	# run command
	. "$GITFLOW_DIR/git-flow-$SUBCOMMAND"
	FLAGS_PARENT="git flow $SUBCOMMAND"

	# test if the first argument is a flag (i.e. starts with '-')
	# in that case, we interpret this arg as a flag for the default
	# command
	SUBACTION="default"
	if [ $SUBCOMMAND != "init" ] && [ "$1" != "" ] && { ! echo "$1" | grep -q "^-"; } then
		SUBACTION="$1"; shift
	fi
	if ! type "cmd_$SUBACTION" >/dev/null 2>&1; then
	    warn "Unknown subcommand: '$SUBACTION'"
    	usage
	   	exit 1
	fi

	# run the specified action
    if [ $SUBACTION != "help" ] && [ $SUBCOMMAND != "init" ] ; then
        init
    fi
    cmd_$SUBACTION "$@"
}

main "$@"
